[package]
name = "phonetics-graph"
version = "0.1.0"
edition = "2021"
default-run = "phonetics-graph"

[dependencies]
rayon = "1.10"
rayon-progress = "1.0"
csv = "1.3"
cudarc = { version = "0.13.6", features = ["cuda-12080"] }
